services:
  auth-service-db:
    image: mysql:8.0
    container_name: chatapp-auth-db
    environment:
      MYSQL_DATABASE: ${AUTH_DB_NAME:-chatapp_auth_service}
      MYSQL_USER: ${AUTH_DB_USER:-chatapp_auth_user}
      MYSQL_PASSWORD: ${AUTH_DB_PASSWORD:-chatapp_auth_password}
      MYSQL_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD:-root_password}
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password # thêm dòng này
    ports:
      - '${AUTH_DB_PORT:-3306}:3306'
    volumes:
      - auth-service-db-data:/var/lib/mysql
    networks:
      - chatapp-network
  user-service-db:
    image: postgres:16
    container_name: chatapp-user-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-chatapp_user_service}
      POSTGRES_USER: ${POSTGRES_USER:-chatapp_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-chatapp_user_password}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - chatapp-user-db-data:/var/lib/postgresql/data
    networks:
      - chatapp-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-chatapp_user}']
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    container_name: chatapp-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    ports:
      - '${RABBITMQ_PORT:-5672}:5672'
      - '${RABBITMQ_MGMT_PORT:-15672}:15672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - chatapp-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  auth-service-db-data:
  chatapp-user-db-data:
  rabbitmq-data:

networks:
  chatapp-network:
    driver: bridge
